<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TheTower.TunnelProtocol</AssemblyName>
    <RootNamespace>TheTower.TunnelProtocol</RootNamespace>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
