schema_version: 1
presets:
  farm_t18:
    - Fleets
    - Boss
    - Elites
    - In Spotlight
    - Tank
    - Closest (Default)
    - Ranged
    - Protector
    - Fast
    - Basic
  farm_t19:
    - Fast
    - Protector
    - Fleets
    - Boss
    - Elites
    - In Spotlight
    - Tank
    - Closest (Default)
    - Ranged
    - Basic
