states:
- name: RUNNING
  type: running
  match_keys:
  - indicators.attack_menu
  - indicators.defense_menu
  - indicators.uw_menu
  - indicators.wall_icon

- name: ATTACK_MENU
  type: menu
  match_keys:
  - indicators.attack_menu

- name: DEFENSE_MENU
  type: menu
  match_keys:
  - indicators.defense_menu

- name: UW_MENU
  type: menu
  match_keys:
  - indicators.uw_menu

- name: HOME_SCREEN
  type: primary
  match_keys:
  - buttons.battle:home

- name: RESUME_GAME
  type: primary
  match_keys:
  - buttons.resume_game

- name: RESUME_BATTLE
  type: primary
  match_keys:
  - buttons.resume_battle

- name: GAME_OVER
  type: primary
  match_keys:
  - indicators.game_over

overlays:
- name: DAILY_GEMS_AVAILABLE
  match_keys:
  - overlays.daily_free_gems_badge

- name: AD_GEMS_AVAILABLE
  match_keys:
  - overlays.claim_ad_gem


