states:
- name: RUNNING
  type: primary
  match_keys:
  - indicators.tournament
  - indicators.menu_attack
  - indicators.menu_defense
  - indicators.menu_utility
  - indicators.menu_uw
  - indicators.cinematic_wall_icon

- name: HOME_SCREEN
  type: primary
  match_keys:
  - indicators.home_screen

- name: GAME_OVER
  type: primary
  match_keys:
  - indicators.game_over

- name: TOURNAMENT
  type: secondary
  match_keys:
  - indicators.tournament

- name: CINEMATIC_MODE
  type: secondary
  match_keys:
  - indicators.cinematic_wall_icon

- name: ATTACK_MENU
  type: menu
  match_keys:
  - indicators.menu_attack

- name: DEFENSE_MENU
  type: menu
  match_keys:
  - indicators.menu_defense

- name: UTILITY_MENU
  type: menu
  match_keys:
  - indicators.menu_utility

- name: UW_MENU
  type: menu
  match_keys:
  - indicators.menu_uw

overlays:
- name: DAILY_GEMS_AVAILABLE
  match_keys:
  - overlays.daily_free_gems_badge

- name: AD_GEMS_AVAILABLE
  match_keys:
  - overlays.ad_gem

- name: MENU_OPEN
  match_keys:
  - overlays.end_round

