states:
- name: RUNNING
  type: primary
  match_keys:
  - indicators.tournament
  - indicators.menu_attack
  - indicators.menu_defense
  - indicators.menu_utility
  - indicators.menu_uw
  - indicators.cinematic_wall_icon
  - overlays.buy_quantity_menu_expanded

- name: HOME_SCREEN
  type: primary
  match_keys:
  - indicators.home_screen

- name: GAME_OVER
  type: primary
  match_keys:
  - indicators.game_over

- name: STORE
  type: primary
  match_keys:
  - indicators.store

- name: DAILY_MISSIONS
  type: primary
  match_keys:
  - indicators.daily_missions

- name: SETTINGS
  type: primary
  match_keys:
  - indicators.settings

- name: CARDS
  type: primary
  match_keys:
  - indicators.cards

- name: LOCKED_CARDS
  type: secondary
  match_keys:
  - indicators.cards:locked

- name: CARDS_GCFARM_LATE
  type: secondary
  match_keys:
  - indicators.cards:deck1

- name: CARDS_GCFARM_EARLY
  type: secondary
  match_keys:
  - indicators.cards:deck3

- name: LAB
  type: primary
  match_keys:
  - indicators.lab

- name: TARGET_PRIORITY
  type: primary
  match_keys:
  - indicators.target_priority

- name: MODULES
  type: primary
  match_keys:
  - indicators.modules

- name: EVENT
  type: primary
  match_keys:
  - indicators.event

- name: DISTANCE_ADJUSTER
  type: primary
  match_keys:
  - indicators.distance_adjuster

- name: GUILD
  type: primary
  match_keys:
  - indicators.guild

- name: TOURNAMENT
  type: secondary
  match_keys:
  - indicators.tournament

- name: CINEMATIC_MODE
  type: secondary
  match_keys:
  - indicators.cinematic_wall_icon

- name: ATTACK_MENU
  type: menu
  match_keys:
  - indicators.menu_attack

- name: DEFENSE_MENU
  type: menu
  match_keys:
  - indicators.menu_defense

- name: UTILITY_MENU
  type: menu
  match_keys:
  - indicators.menu_utility

- name: UW_MENU
  type: menu
  match_keys:
  - indicators.menu_uw

overlays:
- name: DAILY_GEMS_AVAILABLE
  match_keys:
  - overlays.daily_free_gems_badge
  - overlays.daily_free_gems_badge_home

- name: AD_GEMS_AVAILABLE
  match_keys:
  - overlays.ad_gem

- name: MENU_OPEN
  match_keys:
  - overlays.menu_open

- name: MENU_CLOSED
  match_keys:
  - overlays.menu_closed

- name: BUY_QUANTITY_MENU_EXPANDED
  type: overlay
  match_keys:
  - overlays.buy_quantity_menu_expanded

- name: UW_DETAIL
  type: overlay
  match_keys:
  - overlays.uw_detail
