states:
- name: RUNNING
  type: primary
  match_keys:
  - indicators.tournament
  - indicators.menu_attack
  - indicators.menu_defense
  - indicators.menu_utility
  - indicators.menu_uw
  - indicators.cinematic_wall_icon
  - overlays.buy_quantity_menu_expanded

- name: WAVE_PANEL
  type: primary
  match_keys:
  - indicators.wave_panel

- name: PERKS
  type: primary
  match_keys:
  - indicators.perks_panel

- name: HOME_SCREEN
  type: primary
  match_keys:
  - indicators.home_screen

- name: WORKSHOP
  type: primary
  match_keys:
  - indicators.workshop

- name: WORKSHOP_FARM_SLOT
  type: secondary
  match_keys:
  - indicators.workshop:farm_slot

- name: GAME_OVER
  type: primary
  match_keys:
  - indicators.game_over

- name: STORE
  type: primary
  match_keys:
  - indicators.store

- name: DAILY_MISSIONS
  type: primary
  match_keys:
  - indicators.daily_missions

- name: SETTINGS
  type: primary
  match_keys:
  - indicators.settings
  - indicators.settings_stats
  - indicators.settings_toggles
  - indicators.settings_language
  - indicators.settings_update_notes
  - indicators.settings_credits
  - indicators.settings_encyclopedia

- name: CARDS
  type: primary
  match_keys:
  - indicators.cards

- name: LOCKED_CARDS
  type: secondary
  match_keys:
  - indicators.cards:locked

- name: CARDS_GCFARM_LATE
  type: secondary
  match_keys:
  - indicators.Cards:GCFarmLate

- name: CARDS_GCFARM_EARLY
  type: secondary
  match_keys:
  - indicators.Cards:GCFarmEarly

- name: CARDS_GC_ACTIVE
  type: secondary
  match_keys:
  - indicators.cards:gc_active

- name: LAB
  type: primary
  match_keys:
  - indicators.lab
  - indicators.lab_select_research
  - indicators.lab_history

- name: TARGET_PRIORITY
  type: primary
  match_keys:
  - indicators.target_priority

- name: MODULES
  type: primary
  match_keys:
  - indicators.modules
  - indicators.modules_information
  - indicators.modules_history

- name: EVENT
  type: primary
  match_keys:
  - indicators.event

- name: EVENT_BOTS_SCREEN
  type: secondary
  match_keys:
  - indicators.event:bots_screen

- name: BOTS_FARM_ACTIVE
  type: secondary
  match_keys:
  - indicators.bots:farm_active

- name: DISTANCE_ADJUSTER
  type: primary
  match_keys:
  - indicators.distance_adjuster

- name: DAMAGE_ADJUSTER
  type: primary
  match_keys:
  - indicators.damage_adjuster

- name: GUILD
  type: primary
  match_keys:
  - indicators.guild

- name: BATTLE_HEAT
  type: primary
  match_keys:
  - indicators.battle_heat
  - indicators.battle_overheat

- name: BATTLE_HISTORY
  type: primary
  match_keys:
  - indicators.battle_history

- name: RANKING
  type: primary
  match_keys:
  - indicators.ranking

- name: INBOX
  type: primary
  match_keys:
  - indicators.inbox

- name: THEMES
  type: primary
  match_keys:
  - indicators.themes

- name: VAULT
  type: primary
  match_keys:
  - indicators.vault

- name: TOURNAMENT_SCREEN
  type: primary
  match_keys:
  - indicators.tournament_screen
  - indicators.tournament_prizes

- name: UPGRADE_DETAIL
  type: fallback_primary
  match_keys:
  - overlays.upgrade_detail
  - overlays.uw_detail

- name: EXIT_BATTLE_DIALOG
  type: fallback_primary
  match_keys:
  - overlays.exit_battle_dialog

- name: GUILD_GUARDIAN_SCREEN
  type: secondary
  match_keys:
  - indicators.guild:guardian_screen

- name: GUARDIAN_FETCH_EQUIPPED
  type: secondary
  match_keys:
  - indicators.guardian:fetch_equipped

- name: GUARDIAN_SUMMON_EQUIPPED
  type: secondary
  match_keys:
  - indicators.guardian:summon_equipped

- name: GUARDIAN_SCOUT_EQUIPPED
  type: secondary
  match_keys:
  - indicators.guardian:scout_equipped

- name: TOURNAMENT
  type: secondary
  match_keys:
  - indicators.tournament

- name: CINEMATIC_MODE
  type: secondary
  match_keys:
  - indicators.cinematic_wall_icon

- name: ATTACK_MENU
  type: menu
  match_keys:
  - indicators.menu_attack

- name: DEFENSE_MENU
  type: menu
  match_keys:
  - indicators.menu_defense

- name: UTILITY_MENU
  type: menu
  match_keys:
  - indicators.menu_utility

- name: UW_MENU
  type: menu
  match_keys:
  - indicators.menu_uw

overlays:
- name: DAILY_GEMS_AVAILABLE
  match_keys:
  - overlays.daily_free_gems_badge
  - overlays.daily_free_gems_badge_home

- name: AD_GEMS_AVAILABLE
  match_keys:
  - overlays.ad_gem

- name: MENU_OPEN
  match_keys:
  - overlays.menu_open

- name: MENU_CLOSED
  match_keys:
  - overlays.menu_closed

- name: BUY_QUANTITY_MENU_EXPANDED
  type: overlay
  match_keys:
  - overlays.buy_quantity_menu_expanded

- name: UPGRADE_DETAIL
  type: overlay
  match_keys:
  - overlays.upgrade_detail
  - overlays.uw_detail

- name: EXIT_BATTLE_DIALOG
  type: overlay
  match_keys:
  - overlays.exit_battle_dialog
